config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "html_first#home"
  get "/guidelines" => "html_first#guidelines", as: "guidelines"
  get "/resources" => "html_first#resources", as: "resources"
    
end

app/views/shared/_base_styles_left_menu.html.erb
<div class="--left-menu"> 
  <div class="pt-6 group-odin">
    <%= Utilities.markdown_menu("docs/base-styles/menu.md",params[:file],params[:folder]).html_safe %>
  </div>
</div>

app/views/shared/_diet_rails_left_menu.html.erb
<div class="--left-menu"> 
  <div class="pt-6 group-odin">
    <%= Utilities.markdown_menu("docs/diet-rails/menu.md",params[:file],params[:folder]).html_safe %>
  </div>
</div>

app/views/shared/_head.html.erb
<title><%= page_title %></title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="<%= page_description %>">
<meta name="turbo-refresh-method" content="morph">
<meta name="turbo-prefetch" content="false">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= render "h1rails/vendor/tailwind_lite" %>
<%= render "h1rails/vendor/base_styles" %>
<%= render "h1rails/vendor/htmx" %>
<%= render "h1rails/vendor/mini" %>
<link rel="stylesheet" href="/vendor/tailwind-lite/1.0.2.css" >
<link href="/stylesheets/base-styles-custom.css<%= cache_buster %>" rel="stylesheet">
<link href="/stylesheets/styles.css<%= cache_buster %>" rel="stylesheet" >
<script src="/js/custom.js<%= cache_buster %>"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;700&display=swap" rel="stylesheet">
<noscript>
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;700&display=swap" rel="stylesheet">
</noscript>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/tomorrow-night-blue.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/languages/erb.min.js"></script>
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
<script async src="https://umami.toniclabshq.com/script.js" data-website-id="e0b4c39b-a89d-4f84-9465-096169b6295c"></script>
<link  href="/vendor/highlight/tomorrow-night-blue.css" rel="stylesheet" media="screen" />

app/views/shared/_html_first_left_menu.html.erb
<div class="--left-menu --narrow">
  <a class="mb-1" href="<%= resources_path %>">
    <span class="underlined-link <%= 'active' if current_page?(resources_path) && !params[:kind] %> ">
      Directory
    </span>
  </a>
  <% if current_page?(resources_path) %>
    <% kinds = ["newsletter","person", "list", "library","writing"] %>
    <ul class="p-2">
      <% kinds.each do |kind| %>
        <a class="text-sm" href="<%= current_url_with(kind:kind) %>">
          <span class="underlined-link <%= 'active' if params[:kind] == kind %>">
            <%= kind.pluralize.titleize %>
          </span>
        </a>
        <% if kind == "library" && params[:kind] == "library" %>
          <% library_tags = ["buildless","web components"] %>
          <ul class="p-2 hidden">
            <%- library_tags.each do |tag| %>
              <a class="truncate text-sm" href="<%= current_url_with(tag:tag) %>">
                <%= tag %>
              </a>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/shared/_mini_left_menu.html.erb
<div class="--left-menu --narrow"> 
  <a href="<%= mini_js_root_path %>" class="anchor-link block <%= 'active' if current_page?(mini_js_root_path) %>">
    <span class="underlined-link">
      About Mini
    </span>
  </a>
  <a href="<%= mini_js_reference_path %>" class="anchor-link block <%= 'active' if current_page?(mini_js_reference_path) %>"> 
    <span class="underlined-link">
      Reference
    </span>
  </a>
  <a href="<%= mini_js_examples_path %>" class="anchor-link block <%= 'active' if current_page?(mini_js_examples_path) %>">
    <span class="underlined-link">
      Examples
    </span>
  </a>
</div>

app/views/shared/_partial_containers.html.erb
<script>
  showingModal = false
</script>

<div id="right-sidebar" class="hidden bg-gray-700 bg-opacity-50 fixed top-0 bottom-0 right-0 left-0 flex justify-center items-center z-20" >
  <div id="right-sidebar-inner" class="shadow bg-white fixed right-0 bottom-0 top-0 flex z-20" style="width:500px">
    <div style="left:-40px" class="cursor-pointer absolute" _= "on click add .hidden to #right-sidebar">
      <%= inline_svg_tag("heroicons/icon-x.svg",class:"w-10 h-10 text-white") %>
    </div>
    <div id="right-sidebar-content">
    </div>
  </div>
</div>

<div class="ui-toasts" :each="toast, index in toasts" >
  <div class="--toast" role="alert"
    :class="el.toastClass"
    :scope
    :load="
      initialdelay = index * 500
      await wait(initialdelay);
      el.toastClass='--animate-in';
      if (toast.disappearing) {
        await wait(2000);
        el.toastClass='--animate-out'
      }
  ">
    <div class="--wrapper" >
      <div class="--content">
        <div class="--dismiss" :click="scope.toastClass='--animate-out';await wait(1000);scope.toastClass='hidden'" >
          <%= inline_svg_tag("heroicons/x-mark.svg") %>
        </div>
        <span class="--title" :text="toast.title">
        </span> 
        <span class="--message" :text="toast.message">
        </span> 
      </div>
    </div>
  </div>
</div>

app/views/shared/_toast.html.erb
<div _="init wait 0.3 seconds then remove .opacity-0 from me then add .toast-animate-in to me then wait 3 seconds <%=  'then add .toast-animate-out to me' unless local_assigns[:persistent] %>" class="opacity-0 toast p-4 mb-4 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-blue-200 dark:text-blue-800" role="alert">
  <div class="cursor-pointer absolute top-0 right-0" _="on click add .toast-animate-out to the closest .toast then wait 0.5 seconds then remove the closest .toast">
    <%= inline_svg_tag("heroicons/x-mark.svg",class:"w-5 h-5 mt-2 mr-2") %>
  </div>
  <% if defined?(title) && title %>
    <span class="block font-bold mb-2">
      <%= title %>
    </span> 
  <% end %>  
  <% if defined?(message) && message %>
    <%= message %>
  <% end %>
</div>

app/views/shared/_top_bar.html.erb
<div class="sticky top-0 right-0 left-0 bg-white z-20" style="height:60px; box-shadow: 0 0 0.5rem rgba(0, 0, 0, 0.1)">
  <div class="flex justify-between h-full">
    <div class="flex items-center px-2">
      <%= image_tag active_site["logo_path"] %>
    </div>
    <div class="flex items-center">
      <%- sites.each do |site| %>
        <% active = site == active_site %>
        <% is_local? ? domain = site["local"] : domain = site["domain"] %>
        <a class="hover:bg-gray-100 flex h-full px-3 py-1 <%= 'bg-gray-100' if active %>" href="<%= protocol %><%= domain %>">
          <%= image_tag site["logo_path"]+cache_buster, class: "my-3" %>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_top_section.html.erb
<div class="flex justify-between items-center py-5">
  <h1 class="text-3xl font-bold border-b-0 text-black">
    <%= @page_title %>
  </h1>
  <div class="ui-tabnav --ares gap-x-3">
    <div class="<%= 'active' if current_page?(root_path) %>">
      <a class="anchor-link mb-1" href="<%= root_path %>#intro">
        Intro
      </a>
    </div>
    <div class="<%= 'active' if current_page?(guidelines_path) %>">
      <a  href="<%= guidelines_path %>">
        Best Practices
      </a>
    </div>
    <div class="<%= 'active' if current_page?(resources_path) %>">
      <a class="mb-1" href="<%= resources_path %>">
        Directory
      </a>
    </div>
  </div>
</div>